#!/usr/bin/env bash

docker run -ti --rm -e DISPLAY=$DISPLAY --net="host" -v /tmp/.X11-unix:/tmp/.X11-unix -v $HOME/.Xauthority:/home/vivado/.Xauthority -v $(pwd):/home/vivado/project  -v /tools/Xilinx/PetaLinux:/tools/Xilinx/PetaLinux hokim72/petalinux:2022.2 /bin/bash
